#Update an exisit patients.
PUT http://localhost:4000/patients/547900cb-8b3e-42e6-b7a9-78af78c21708
Content-Type: application/json

{
  "name": "Puttar Punjabi",
  "address": "Rawalpindi",
  "email": "puttarpunjabi@gmail.com",
  "dateOfBirth": "1992-10-01"

}
